# Site settings
author: Drew Hadley
title: Even Androids Can Cry!
header-img: img/home-bg.png
email: drewhadley.guitar@gmail.com
copyright_name: Drew Hadley
description: > # this means to ignore newlines until "baseurl:"
  Adventures and misadventures in the world of software engineering 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  VandelayUtd

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
